const songs=[
{t:"Uga Hai Suraj Dev",a:"Anuradha Paudwal",c:"Paramparik Geet",v:"8MzoVsjL4QU"},
{t:"Rovele Banjhiniya",a:"Akshara Singh",c:"New Chhath Geet",v:"REPLACE_ID_2"},
{t:"Jode Jode Falwa",a:"Pawan Singh",c:"New Chhath Geet",v:"REPLACE_ID_3"},
{t:"Chhath Ghate Chali",a:"Khesari Lal Yadav & Antra Singh Priyanka",c:"New Chhath Geet",v:"REPLACE_ID_4"},
{t:"Chahi Na Ann Dhan Khajanwa",a:"Arvind Akela Kallu",c:"Paramparik Geet",v:"REPLACE_ID_5"},
{t:"Chhath Mai Ke Baratiya",a:"Khesari Lal Yadav",c:"New Chhath Geet",v:"REPLACE_ID_6"},
{t:"Kaanch Hi Baans Ke Bahangiya",a:"Anuradha Paudwal",c:"Paramparik Geet",v:"REPLACE_ID_7"},
{t:"Kelwa Ke Paat Par",a:"Sharda Sinha",c:"Argh Songs",v:"REPLACE_ID_8"}];
let cat="All",cur=-1;const ⁸;
function render(){let q=document.querySelector("#search").value.toLowerCase();let x=songs.filter(s=>(cat=="All"||s.c==cat)&&(`${s.t} ${s.a}`.toLowerCase().includes(q)));list.innerHTML=x.map(s=>{let i=songs.indexOf(s);let img=s.v.startsWith("REPLACE_")?"":`https://i.ytimg.com/vi/${s.v}/hqdefault.jpg`;return `<div class="song ${i==cur?"selected":""}"><span>${String(i+1).padStart(2,"0")}</span>${img?`<img class="cover" src="${img}">`:`<div class="cover" style="display:grid;place-items:center;font-size:28px">☀</div>`}<div class="info"><b>${s.t}</b><small>${s.a}</small></div><button class="heart">♡</button><button class="play" data-i="${i}">▶</button></div>`}).join("")||"<p>No geet found</p>"}function play(i){let s=songs[i];cur=i;document.querySelector("#title").firstChild.textContent=s.t;document.querySelector("#artist").textContent=s.a;if(s.v.startsWith("REPLACE_")){alert("script.js me is song ka YouTube Video ID paste karo.");return}document.querySelector("#yt").src=`https://www.youtube.com/embed/${s.v}?autoplay=1&rel=0`;render()}list.addEventListener("click",e=>{let b=e.target.closest(".play");if(b)play(+b.dataset.i)});document.querySelector("#search").oninput=render;document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.c;render()});document.querySelector("#open").onclick=()=>document.querySelector(".playlist").scrollIntoView({behavior:"smooth"});document.querySelector("#close").onclick=()=>document.querySelector("#yt").src="";render();
