const KEY='jee370rTrackerV4', OLD='jee370rTrackerV3';
const fields=['date','lec','phyWork','chemWork','mathWork','phyDpp','chemDpp','mathDpp','phyPyq','chemPyq','mathPyq'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const num=v=>{const m=String(v||'').match(/\d+/);return m?+m[0]:0};
const today=()=>new Date().toISOString().slice(0,10);
const fmtMin=m=>{m=Math.max(0,Math.round(m));return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2200)}
function put(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function combine(a,b){a=String(a||'').trim();b=String(b||'').trim();return a&&b?`${a} + ${b}`:a||b}
function rowsData(){return $$('#tracker tbody tr').map(tr=>Object.fromEntries($$('input',tr).map(i=>[i.dataset.f,i.value])))}
function makeRows(){const tb=$('#tracker tbody');tb.innerHTML='';addRows(15)}
function addRows(n=15){const tb=$('#tracker tbody');const start=tb.children.length;for(let i=0;i<n;i++){const tr=document.createElement('tr');tr.dataset.i=start+i;tr.innerHTML=fields.map((f,j)=>`<td><input data-f="${f}" ${j===0?'type="date"':''} inputmode="numeric"></td>`).join('');tb.appendChild(tr);$$('input',tr).forEach(i=>i.addEventListener('input',()=>{updateStats();autoExtendRows()}))}}
function autoExtendRows(){const rows=$$('#tracker tbody tr');if(rows.slice(-3).some(r=>$$('input',r).some(i=>i.value.trim())))addRows(15)}
function sumField(data,f){return data.reduce((s,r)=>s+num(r[f]),0)}
function updateStats(){const d=rowsData(),done=d.filter(r=>Object.values(r).some(v=>String(v||'').trim())).length;const phyWork=sumField(d,'phyWork'),chemWork=sumField(d,'chemWork'),mathWork=sumField(d,'mathWork'),phyDpp=sumField(d,'phyDpp'),chemDpp=sumField(d,'chemDpp'),mathDpp=sumField(d,'mathDpp'),phyPyq=sumField(d,'phyPyq'),chemPyq=sumField(d,'chemPyq'),mathPyq=sumField(d,'mathPyq');const phy=phyWork+phyDpp+phyPyq,chem=chemWork+chemDpp+chemPyq,math=mathWork+mathDpp+mathPyq,total=phy+chem+math,pyq=phyPyq+chemPyq+mathPyq,avg=done?Math.round(total/done):0;put('daysDone',done);put('lecSum',sumField(d,'lec'));put('questionSum',total);put('pyqSum',pyq);put('avgQ',avg);put('qTarget',done?Math.min(100,Math.round(total/(done*70)*100))+'%':'0%');[['phyWorkSum',phyWork],['chemWorkSum',chemWork],['mathWorkSum',mathWork],['workSum',phyWork+chemWork+mathWork],['phyDppSum',phyDpp],['chemDppSum',chemDpp],['mathDppSum',mathDpp],['dppSum',phyDpp+chemDpp+mathDpp],['phyPyqSum',phyPyq],['chemPyqSum',chemPyq],['mathPyqSum',mathPyq],['pyqDetailSum',pyq],['phyTotal',phy],['chemTotal',chem],['mathTotal',math],['overallTotal',total]].forEach(x=>put(x[0],x[1]));updateDashboard()}
function migrate(){let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.rows)return x;x=JSON.parse(localStorage.getItem(OLD)||'null');return x?.rows?x:null}
function save(silent=false){localStorage.setItem(KEY,JSON.stringify({version:4,startDate:$('#startDate')?.value||'',examDate:$('#examDate')?.value||'',rows:rowsData()}));if(!silent)toast('Saved on this device ✓')}
function load(){const x=migrate();if(!x)return toast('No saved tracker found');$('#startDate').value=x.startDate||'';if(x.examDate)$('#examDate').value=x.examDate;makeRows();x.rows.forEach((o,i)=>{while(i>=$('#tracker tbody').children.length)addRows(15);fields.forEach(f=>{const e=$(`#tracker tbody tr:nth-child(${i+1}) [data-f="${f}"]`);if(e)e.value=o[f]||''})});updateStats();toast('Tracker loaded ✓')}
function clearAll(){if(!confirm('Clear all study tracker rows?'))return;localStorage.removeItem(KEY);makeRows();updateStats();toast('Tracker cleared')}
function fillDates(){const s=$('#startDate').value;if(!s)return toast('Select a start date first');const d=new Date(s+'T00:00:00');$$('#tracker tbody tr').forEach((tr,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);tr.querySelector('[data-f="date"]').value=x.toISOString().slice(0,10)});updateStats()}
function updateCountdown(){const v=$('#examDate').value;if(!v)return;const t=new Date(v+'T00:00:00'),n=new Date();t.setHours(0,0,0,0);n.setHours(0,0,0,0);const days=Math.ceil((t-n)/864e5);put('countdown',days>0?`${days} DAYS LEFT`:days===0?'EXAM DAY':'DATE PASSED');put('examDateLabel',t.toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'}))}

// Navigation
function openPage(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+page));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'});if(page==='analytics')renderAnalytics()}
$$('.nav-item').forEach(n=>n.addEventListener('click',()=>openPage(n.dataset.page)));$$('[data-page]').forEach(n=>{if(!n.classList.contains('nav-item'))n.addEventListener('click',()=>openPage(n.dataset.page))});$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')};$('#closeMenu').onclick=()=>{$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')};$('#backdrop').onclick=()=>{$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')};

// Tasks
let tasks=JSON.parse(localStorage.getItem('jeeTasksV1')||'[]');
function saveTasks(){localStorage.setItem('jeeTasksV1',JSON.stringify(tasks));renderTasks();updateDashboard()}
function renderTasks(){const selected=$('#plannerDate')?.value||today();const list=$('#taskList');if(list)list.innerHTML='';const filtered=tasks.filter(t=>t.date===selected);filtered.forEach(t=>{const el=document.createElement('div');el.className='task-item';el.innerHTML=`<input class="task-check" type="checkbox" ${t.done?'checked':''} data-id="${t.id}"><div><div class="task-title ${t.done?'done':''}">${escapeHtml(t.title)}</div><div class="task-meta">${t.subject} · <span class="priority-${t.priority.toLowerCase()}">${t.priority}</span> · ${t.minutes||0} min</div></div><div class="task-actions"><button class="icon-btn edit-task" data-id="${t.id}">✎</button><button class="icon-btn del-task" data-id="${t.id}">×</button></div>`;list?.appendChild(el)});$$('.task-check').forEach(e=>e.onchange=()=>{const t=tasks.find(x=>x.id==e.dataset.id);if(t)t.done=e.checked;saveTasks()});$$('.del-task').forEach(e=>e.onclick=()=>{tasks=tasks.filter(x=>x.id!=e.dataset.id);saveTasks()});$$('.edit-task').forEach(e=>e.onclick=()=>editTask(e.dataset.id));updatePlannerStats()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function editTask(id){const t=tasks.find(x=>x.id==id);if(!t)return;const title=prompt('Task title',t.title);if(title===null)return;t.title=title.trim()||t.title;saveTasks()}
$('#addTaskBtn').onclick=()=>{const title=$('#taskTitle').value.trim();if(!title)return toast('Enter a task title');tasks.push({id:Date.now(),title,subject:$('#taskSubject').value,priority:$('#taskPriority').value,date:$('#taskDate').value||today(),repeat:$('#taskRepeat').value,minutes:+$('#taskMinutes').value||0,done:false});$('#taskTitle').value='';$('#taskMinutes').value='';saveTasks();toast('Task added ✓')};$('#plannerDate').value=today();$('#plannerDate').onchange=renderTasks;$('#taskDate').value=today();
function updatePlannerStats(){const t=today(),pending=tasks.filter(x=>!x.done).length,due=tasks.filter(x=>!x.done&&x.date===t).length,over=tasks.filter(x=>!x.done&&x.date<t).length,complete=tasks.filter(x=>x.done).length;put('pendingCount',pending);put('dueCount',due);put('overdueCount',over);put('completedCount',complete);put('plannerRange','Today · '+new Date(t+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}))}

// Focus
let focusLogs=JSON.parse(localStorage.getItem('jeeFocusV2')||'[]'),timer={running:false,paused:false,startedAt:0,elapsed:0,interval:null};
function currentElapsed(){return timer.elapsed+(timer.running&&!timer.paused?Math.floor((Date.now()-timer.startedAt)/1000):0)}
function drawTimer(){const sec=currentElapsed(),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;put('timerDisplay',[h,m,s].map(x=>String(x).padStart(2,'0')).join(':'));put('timerStatus',timer.running?(timer.paused?'PAUSED':'FOCUSING'):'READY');const deg=Math.min(359,(sec%3600)/3600*360);$('.timer-ring').style.background=`conic-gradient(#566b9f ${deg}deg,#d9def3 ${deg}deg)`;put('timerSub',timer.running?$('#focusChapter').value||$('#focusActivity').value:'Choose a subject and start.')}
function startFocus(){if(!timer.running){timer.running=true;timer.paused=false;timer.startedAt=Date.now();timer.elapsed=0}else if(timer.paused){timer.paused=false;timer.startedAt=Date.now()}clearInterval(timer.interval);timer.interval=setInterval(drawTimer,500);drawTimer();toast('Focus started 🔥');broadcastRoom()}
function pauseFocus(){if(!timer.running)return;if(!timer.paused){timer.elapsed=currentElapsed();timer.paused=true;clearInterval(timer.interval)}drawTimer();toast('Focus paused');broadcastRoom()}
function finishFocus(){if(!timer.running)return;const sec=currentElapsed();if(sec<5)return toast('Study a little longer before saving');const log={id:Date.now(),date:today(),subject:$('#focusSubject').value,activity:$('#focusActivity').value,chapter:$('#focusChapter').value,questions:+$('#focusQuestions').value||0,minutes:Math.max(1,Math.round(sec/60))};focusLogs.unshift(log);localStorage.setItem('jeeFocusV2',JSON.stringify(focusLogs));timer={running:false,paused:false,startedAt:0,elapsed:0,interval:null};drawTimer();renderFocus();updateDashboard();broadcastRoom();toast('Focus session saved ✓')}
$('#focusStart').onclick=startFocus;$('#focusPause').onclick=pauseFocus;$('#focusFinish').onclick=finishFocus;['focusSubject','focusActivity','focusChapter'].forEach(id=>$('#'+id).addEventListener('input',drawTimer));
function renderFocus(){const el=$('#focusHistory');if(!el)return;el.innerHTML='';focusLogs.slice(0,15).forEach(l=>{const x=document.createElement('div');x.className='focus-entry';x.innerHTML=`<div><strong>${escapeHtml(l.subject)} · ${escapeHtml(l.activity)}</strong><small>${escapeHtml(l.chapter||'')} ${l.questions?' · '+l.questions+' questions':''}</small></div><b>${fmtMin(l.minutes)}</b><button class="icon-btn" data-focus-id="${l.id}">×</button>`;el.appendChild(x)});$$('[data-focus-id]').forEach(b=>b.onclick=()=>{focusLogs=focusLogs.filter(x=>x.id!=b.dataset.focusId);localStorage.setItem('jeeFocusV2',JSON.stringify(focusLogs));renderFocus();updateDashboard()});const mins=focusLogs.filter(x=>x.date===today()).reduce((s,x)=>s+x.minutes,0);put('focusTotalBadge',fmtMin(mins)+' today')}

// Dashboard
function totalFocusToday(){return focusLogs.filter(x=>x.date===today()).reduce((s,x)=>s+x.minutes,0)}
function updateDashboard(){const mins=totalFocusToday(),t=tasks.filter(x=>x.date===today()),done=t.filter(x=>x.done).length;put('dashFocus',fmtMin(mins));put('dashQuestions',focusLogs.filter(x=>x.date===today()).reduce((s,x)=>s+x.questions,0));put('dashTasks',`${done} / ${t.length}`);$('#focusProgress').style.width=Math.min(100,mins/480*100)+'%';const tl=$('#dashTasksList');if(tl){tl.innerHTML='';t.slice(0,5).forEach(x=>{const e=document.createElement('div');e.className='task-item';e.innerHTML=`<input class="task-check" type="checkbox" ${x.done?'checked':''} disabled><div><div class="task-title">${escapeHtml(x.title)}</div><div class="task-meta">${x.subject} · ${x.priority}</div></div><b>${x.done?'✓':'→'}</b>`;tl.appendChild(e)});if(!t.length)tl.innerHTML='<div class="task-meta">No tasks for today. Add one in Daily Planner.</div>'}const fl=$('#dashFocusList');if(fl){fl.innerHTML='';focusLogs.filter(x=>x.date===today()).slice(0,5).forEach(x=>{const e=document.createElement('div');e.className='focus-entry';e.innerHTML=`<div><strong>${escapeHtml(x.subject)} · ${escapeHtml(x.activity)}</strong><small>${escapeHtml(x.chapter||'')}</small></div><b>${fmtMin(x.minutes)}</b>`;fl.appendChild(e)});if(!focusLogs.filter(x=>x.date===today()).length)fl.innerHTML='<div class="task-meta">No focus session today.</div>'} }

// Study room (local same-device realtime demo)
let room=JSON.parse(localStorage.getItem('jeeRoomV1')||'null')||{code:'',name:'',user:'Student',members:{}};let bc='BroadcastChannel' in window?new BroadcastChannel('jee-study-room'):null;
function saveRoom(){localStorage.setItem('jeeRoomV1',JSON.stringify(room));renderRoom();broadcastRoom()}
function broadcastRoom(){if(bc)bc.postMessage({room,focus:timer.running&&!timer.paused?currentElapsed():0,user:room.user})}
if(bc)bc.onmessage=e=>{if(e.data?.room?.code===room.code){room=e.data.room;const u=e.data.user;if(u&&u!==room.user&&e.data.focus)room.members[u]={name:u,status:'focus',seconds:e.data.focus};renderRoom()}}
function createRoom(){const name=$('#roomName').value.trim()||'JEE Study Room';const user=$('#roomUser').value.trim()||'Student';room={code:Math.random().toString(36).slice(2,8).toUpperCase(),name,user,members:{}};room.members[user]={name:user,status:'focus',seconds:0};saveRoom();toast('Room created ✓')}
function joinRoom(){const code=$('#roomCode').value.trim().toUpperCase();if(!code)return toast('Enter a room code');room={code,name:$('#roomName').value.trim()||'Study Room',user:$('#roomUser').value.trim()||'Student',members:{}};room.members[room.user]={name:room.user,status:'offline',seconds:0};saveRoom();toast('Joined room ✓')}
$('#createRoom').onclick=createRoom;$('#joinRoom').onclick=joinRoom;
function renderRoom(){put('roomTitle',room.name||'Study Room');put('roomCodeBox',room.code?'ROOM CODE: '+room.code:'No room joined');const list=$('#roomMembers');if(!list)return;const members=Object.values(room.members||{});list.innerHTML='';let total=0;members.sort((a,b)=>b.seconds-a.seconds).forEach(m=>{total+=m.seconds;const e=document.createElement('div');e.className='member';const cls=m.status==='focus'?'status-focus':m.status==='break'?'status-break':'status-off';e.innerHTML=`<div class="member-name">${escapeHtml(m.name)} ${m.name===room.user?'(you)':''}</div><span class="status-dot ${cls}">${m.status==='focus'?'🟢 Focusing':m.status==='break'?'🟡 Break':'⚪ Offline'}</span><span class="member-time">${fmtMin(Math.round(m.seconds/60))}</span>`;list.appendChild(e)});put('roomTotal',fmtMin(Math.round(total/60)));if(!members.length)list.innerHTML='<div class="task-meta">Create or join a room to see members.</div>'}
setInterval(()=>{if(room.code&&room.user){room.members[room.user]={name:room.user,status:timer.running?(timer.paused?'break':'focus'):'offline',seconds:Math.round(totalFocusToday()*60+currentElapsed())};localStorage.setItem('jeeRoomV1',JSON.stringify(room));renderRoom();broadcastRoom()}},1000);

// Analytics
function renderAnalytics(){const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days.push(d.toISOString().slice(0,10))}const bars=$('#focusBars');bars.innerHTML='';const vals=days.map(d=>focusLogs.filter(x=>x.date===d).reduce((s,x)=>s+x.minutes,0)),max=Math.max(60,...vals);vals.forEach((v,i)=>{const e=document.createElement('div');e.className='bar-wrap';e.innerHTML=`<div class="bar"><i style="height:${v/max*100}%"></i></div><small>${days[i].slice(5)}</small><b>${v}m</b>`;bars.appendChild(e)});const mix={};focusLogs.forEach(x=>mix[x.activity]=(mix[x.activity]||0)+x.minutes);const total=Object.values(mix).reduce((a,b)=>a+b,0)||1;const ml=$('#activityMix');ml.innerHTML='';Object.entries(mix).sort((a,b)=>b[1]-a[1]).slice(0,8).forEach(([k,v])=>{const e=document.createElement('div');e.className='mix-row';e.innerHTML=`<span>${escapeHtml(k)}</span><div class="line"><i style="width:${v/total*100}%"></i></div><b>${fmtMin(v)}</b>`;ml.appendChild(e)})}

// JSON/PDF
function exportJSON(){const payload={version:4,exportedAt:new Date().toISOString(),tracker:{startDate:$('#startDate').value,examDate:$('#examDate').value,rows:rowsData()},tasks,focusLogs,room};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='jee-tracker-backup.json';a.click()}
function importJSON(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.tracker?.rows){localStorage.setItem(KEY,JSON.stringify({startDate:x.tracker.startDate||'',examDate:x.tracker.examDate||'',rows:x.tracker.rows}));if(x.tasks)localStorage.setItem('jeeTasksV1',JSON.stringify(x.tasks));if(x.focusLogs)localStorage.setItem('jeeFocusV2',JSON.stringify(x.focusLogs));location.reload()}else throw 0}catch(e){toast('Invalid JSON backup')}};r.readAsText(file)}
function makePDF(){const L=window.jspdf?.jsPDF;if(!L)return toast('PDF library missing');const pdf=new L({orientation:'landscape',unit:'mm',format:'a4'});const d=rowsData().slice(0,15),cols=['DATE','LEC','PHY HW','CHEM HW','MATH HW','PHY DPP','CHEM DPP','MATH DPP','PHY PYQ','CHEM PYQ','MATH PYQ'];pdf.setFontSize(16);pdf.text('370R JEE ADVANCED TRACKER',14,14);pdf.setFontSize(9);pdf.text(`Questions: ${sumField(d,'phyWork')+sumField(d,'chemWork')+sumField(d,'mathWork')+sumField(d,'phyDpp')+sumField(d,'chemDpp')+sumField(d,'mathDpp')+sumField(d,'phyPyq')+sumField(d,'chemPyq')+sumField(d,'mathPyq')}   Lectures: ${sumField(d,'lec')}`,14,20);pdf.autoTable({startY:25,head:[cols],body:d.map(r=>fields.map(f=>r[f]||'')),theme:'grid',styles:{fontSize:7,halign:'center'},headStyles:{fillColor:[255,154,180],textColor:[52,66,102]}});pdf.save('370R-JEE-Tracker.pdf')}
async function monthlyPDF(){const key=$('#reportMonth').value;if(!key)return toast('Select report month');const d=rowsData().filter(r=>String(r.date).slice(0,7)===key);if(!d.length)return toast('No data for this month');const L=window.jspdf.jsPDF,pdf=new L({orientation:'landscape',unit:'mm',format:'a4'});pdf.setFontSize(16);pdf.text(`370R JEE Tracker — ${key}`,14,14);pdf.autoTable({startY:20,head:[fields.map(f=>f.toUpperCase())],body:d.map(r=>fields.map(f=>r[f]||'')),theme:'grid',styles:{fontSize:7}});pdf.save(`JEE-Tracker-${key}.pdf`)}

// Init
$('#saveBtn').onclick=()=>save();$('#loadBtn').onclick=load;$('#clearBtn').onclick=clearAll;$('#datesBtn').onclick=fillDates;$('#addBtn').onclick=()=>addRows(15);$('#pdfBtn').onclick=makePDF;$('#monthPdfBtn').onclick=monthlyPDF;$('#jsonExportBtn').onclick=exportJSON;$('#jsonImport').onchange=e=>e.target.files[0]&&importJSON(e.target.files[0]);$('#examDate').onchange=()=>{updateCountdown();save(true)};
$('#todayChip').textContent=new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});makeRows();const old=migrate();if(old){$('#startDate').value=old.startDate||'';if(old.examDate)$('#examDate').value=old.examDate;old.rows.forEach((o,i)=>{while(i>=$('#tracker tbody').children.length)addRows(15);fields.forEach(f=>{const e=$(`#tracker tbody tr:nth-child(${i+1}) [data-f="${f}"]`);if(e)e.value=o[f]||''})})}updateCountdown();updateStats();renderTasks();renderFocus();renderRoom();drawTimer();
